name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      
      # Get dependencies
      - run: flutter pub get
      
      # Verify formatting
      - run: flutter format --set-exit-if-changed .
      
      # Analyze the Dart code
      - run: flutter analyze
      
      # Make shell script executable (important for tests)
      - run: chmod +x export_icon.sh
      
      # Run tests
      - run: flutter test
      
      # Build web version (to make sure it compiles)
      - run: flutter build web 