name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true
      
      # Get dependencies
      - name: Install dependencies
        run: flutter pub get
      
      # Verify formatting
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
      
      # Analyze the Dart code
      - name: Analyze code
        run: flutter analyze --fatal-infos
      
      # Run tests
      - name: Run tests
        run: flutter test
      
      # Build web version
      - name: Build web
        run: flutter build web --release 